on:
  pull_request:
    branches: [main]
    types: [opened, labeled, unlabeled, reopened]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: sugarshin/required-labels-action@v0.3.1
        with:
          required_oneof: 'backport: auto,backport: skip'
