name: release-kibana
on:
  workflow_dispatch:
    inputs:
      kibana_branch:
        description: 'Target branch for a Kibana PR'
        required: true
        default: 'master'
      labels:
        description: 'Additional labels to assign to the PR'
        required: false
      draft:
        description: 'Create a PR as draft (Y)'
        required: false

jobs:
  kibana-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PROTECTIONS_MACHINE_TOKEN }}
          ref: ${{matrix.target_branch}}

      - name: Checkout Kibana
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PROTECTIONS_MACHINE_TOKEN }}
          ref: ${{github.event.inputs.kibana_branch}}
          path: ../kibana

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build release package
        run: |
          python -m detection_rules dev build-release
#
#      - name: Archive production artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: release-files
#          path: |
#            releases

      - name: Set github config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create the PR to Kibana
        env:
          DRAFT_ARGS: "${{startsWith(github.event.inputs.draft,'y') && '--draft' || ' '}}"
          LABEL_ARGS: "--label release_note:skip,${{github.event.inputs.labels}}"
          BRANCH_ARGS: "--base-branch ${{github.event.inputs.kibana_branch}}"
          GITHUB_TOKEN: "${{ secrets.PROTECTIONS_MACHINE_TOKEN }}"
        run: |
          python -m detection_rules dev kibana-pr --assign ${{github.actor}} $LABEL_ARGS $DRAFT_ARGS $BRANCH_ARGS
